Repository sendgrid/sendgrid-java, pull requests merged in 2018-10, with the labels that each got.

#461 Update README to use implementation instead of compile
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#463 Link to the online version of CLA in README.md
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#358 Fixing similar code issue in examples/ips/ips.java
  examples/ips/AddToPool.java
  examples/ips/AddToWarmup.java
  examples/ips/CreatePool.java
  examples/ips/DeletePool.java
  examples/ips/README.md
  examples/ips/RemoveFromPool.java
  examples/ips/RemoveFromWarmup.java
  examples/ips/RetrieveAllIPs.java
  examples/ips/RetrieveAllPools.java
  examples/ips/RetrieveAssignedIPs.java
  examples/ips/RetrieveIPsInPool.java
  examples/ips/RetrieveIPsInWarmup.java
  examples/ips/RetrievePoolsForIP.java
  examples/ips/RetrieveWarmupStatus.java
  examples/ips/UpdatePoolName.java
  examples/ips/ips.java
Labels: difficulty: medium, hacktoberfest, status: cla not signed, status: hacktoberfest approved, type: community enhancement

#475 Fix formatting of README in examples/accesssettings 🎃
  examples/accesssettings/README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#449 Dynamic templates support
  USE_CASES.md
  docker/Dockerfile
  docker/USAGE.md
  examples/helpers/mail/Example.java
  src/main/java/com/sendgrid/helpers/mail/objects/Personalization.java
  src/test/java/com/sendgrid/helpers/MailTest.java
Labels: difficulty: medium, status: ready for deploy, type: community enhancement

#306 Fix java package names
  src/main/java/com/sendgrid/helpers/mail/Mail.java
  src/main/java/com/sendgrid/helpers/mail/objects/ASM.java
  src/main/java/com/sendgrid/helpers/mail/objects/Attachments.java
  src/main/java/com/sendgrid/helpers/mail/objects/BccSettings.java
  src/main/java/com/sendgrid/helpers/mail/objects/ClickTrackingSetting.java
  src/main/java/com/sendgrid/helpers/mail/objects/Content.java
  src/main/java/com/sendgrid/helpers/mail/objects/Email.java
  src/main/java/com/sendgrid/helpers/mail/objects/FooterSetting.java
  src/main/java/com/sendgrid/helpers/mail/objects/GoogleAnalyticsSetting.java
  src/main/java/com/sendgrid/helpers/mail/objects/MailSettings.java
  src/main/java/com/sendgrid/helpers/mail/objects/OpenTrackingSetting.java
  src/main/java/com/sendgrid/helpers/mail/objects/Personalization.java
  src/main/java/com/sendgrid/helpers/mail/objects/Setting.java
  src/main/java/com/sendgrid/helpers/mail/objects/SpamCheckSetting.java
  src/main/java/com/sendgrid/helpers/mail/objects/SubscriptionTrackingSetting.java
  src/main/java/com/sendgrid/helpers/mail/objects/TrackingSettings.java
  src/test/java/com/sendgrid/TestRequiredFilesExist.java
  src/test/java/com/sendgrid/helpers/AttachmentBuilderTest.java
  src/test/java/com/sendgrid/helpers/ContentTest.java
  src/test/java/com/sendgrid/helpers/MailTest.java
  src/test/java/com/sendgrid/helpers/mail/objects/SettingsSerializationTest.java
Labels: difficulty: medium, status: ready for deploy, type: community enhancement

#500 Update CONTRIBUTING - using gitflow workflow, development branch inst…
  .github/PULL_REQUEST_TEMPLATE
  CONTRIBUTING.md
Labels: difficulty: easy, good first issue, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update
