Repository sendgrid/sendgrid-java, pull requests merged in 2020-07, with the labels that each got.

#635 fix: don't use dependency version ranges
  pom.xml
Labels: status: code review request

#637 docs: fix the kitchen sink example and link to it in the use cases doc
  USE_CASES.md
  examples/accesssettings/DeleteIPFromAccessSettings.java
  examples/helpers/mail/Example.java
  examples/ips/RetrieveAllPools.java
  examples/temp.txt
  examples/temp2.txt
Labels: status: code review request

#638 docs: add multi-recipient examples
  USE_CASES.md
  examples/helpers/mail/MultipleEmailsMultipleRecipients.java
  examples/helpers/mail/SingleEmailMultipleRecipients.java
Labels: status: code review request

#639 chore: migrate to new default sendgrid-oai branch
  Makefile
Labels: status: code review request

#643 fix: Replace `bcprov-jdk15to18` with `bcprov-jdk15on`
  pom.xml
Labels: status: code review request

#390 docs: Update README link to avoid redirection
  bin/com/sendgrid/helpers/README.md
Labels: difficulty: easy, status: code review request, type: docs update

#370 docs: breakup examples to their own files in examples/user/user.java
  examples/user/CreateWebhookParseSettings.java
  examples/user/DeleteScheduleSend.java
  examples/user/DeleteWebhookParseSettings.java
  examples/user/GetCreditBalance.java
  examples/user/GetEmailAddress.java
  examples/user/GetEnforedTLS.java
  examples/user/GetProfile.java
  examples/user/GetScheduleSend.java
  examples/user/GetScheduleSendByBatchId.java
  examples/user/GetUserInfo.java
  examples/user/GetUsername.java
  examples/user/GetWebhookEventSettings.java
  examples/user/GetWebhookParseSettingByHostname.java
  examples/user/GetWebhookParseSettings.java
  examples/user/GetWebhookParseStatistics.java
  examples/user/PauseScheduleSend.java
  examples/user/README.md
  examples/user/TestWebhookEvent.java
  examples/user/UpdateEmailAddress.java
  examples/user/UpdateEnforcedTLS.java
  examples/user/UpdatePassword.java
  examples/user/UpdateProfile.java
  examples/user/UpdateScheduleSend.java
  examples/user/UpdateUsername.java
  examples/user/UpdateWebhookEventSettings.java
  examples/user/UpdateWebhookParseSettings.java
  examples/user/user.java
Labels: difficulty: medium, status: code review request
