Repository sendgrid/sendgrid-java, pull requests merged in 2020-11, with the labels that each got.

#357 docs: Fix code issues in examples/clients/clients.java
  examples/clients/GetEmailStatistics.java
  examples/clients/GetEmailStatisticsByClientType.java
  examples/clients/README.md
  examples/clients/clients.java
Labels: difficulty: medium, status: code review request

#304 docs: Save attachment to Dropbox
  examples/dropbox/UploadToDropBox.java
Labels: difficulty: hard, status: code review request

#628 docs: Correct number of free emails
  README.md
Labels: status: code review request

#418 docs: Fixes Javadoc errors in Attachments.java
  src/main/java/com/sendgrid/helpers/mail/objects/Attachments.java
Labels: difficulty: easy, status: code review request

#405 docs: Create use-cases directory
  USE_CASES.md
  use-cases/README.md
  use-cases/domain-authentication.md
  use-cases/email-statistics.md
  use-cases/transactional-templates.md
Labels: difficulty: easy, status: code review request

#292 feat: Add helper for get unassigned IPs
  src/main/java/com/sendgrid/helpers/ips/IPAddress.java
  src/main/java/com/sendgrid/helpers/ips/IPsHelper.java
Labels: difficulty: medium, status: code review request

#656 docs: Fix broken link in readme
  README.md
Labels: status: code review request
