Repository sendgrid/sendgrid-java, pull requests merged in 2020-08, with the labels that each got.

#644 chore: update GitHub branch references to use HEAD
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  TROUBLESHOOTING.md
  USAGE.md
  USE_CASES.md
  bin/com/sendgrid/helpers/README.md
  examples/mail/mail.java
  pom.xml
  src/main/java/com/sendgrid/helpers/README.md
  twilio_sendgrid_logo.png
Labels: status: code review request

#496 test: Add spotbugs and checkstyle maven plugins for Travis CI
  Makefile
  pom.xml
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved

#491 docs: add contribution guide for first-timers
  first-timers.md
  static/img/github-fork.png
  static/img/github-sign-up.png
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved

#477 doc: Run *.md documents through Grammer.ly
  CHANGELOG.md
  CONTRIBUTING.md
  TROUBLESHOOTING.md
  USAGE.md
  USE_CASES.md
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved, type: docs update
