Repository sendgrid/sendgrid-java, pull requests merged in 2020-02, with the labels that each got.

#590 docs: fix typo in README
  README.md
Labels: status: code review request

#563 chore: Remove unnecessary access modifiers on interface methods.
  src/main/java/com/sendgrid/APICallback.java
  src/main/java/com/sendgrid/SendGridAPI.java
Labels: status: code review request

#542 chore: Removed the apiKey instance variable as it wasn't being used
  src/main/java/com/sendgrid/SendGrid.java
Labels: difficulty: easy, status: code review request, status: hacktoberfest approved

#387 docs: makes Environmental Variables a sub topic in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: difficulty: easy, status: code review request, type: docs update

#603 docs: baseline all the templated markdown docs
  .github/ISSUE_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  LICENSE.md
  PULL_REQUEST_TEMPLATE.md
  src/test/java/com/sendgrid/LicenseTest.java
  src/test/java/com/sendgrid/TestRequiredFilesExist.java
Labels: status: code review request

#534 docs: Fix whitespace errors and typos
  .github/PULL_REQUEST_TEMPLATE
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: difficulty: easy, status: code review request, status: hacktoberfest approved

#402 docs: Add Code Review to Contributing.md
  CONTRIBUTING.md
Labels: difficulty: easy, status: code review request, type: docs update

#604 docs: Fix GitHub spelling
  CONTRIBUTING.md
Labels: status: code review request

#608 fix: update release jar
  Makefile
  pom.xml
Labels: status: code review request

#540 docs: Update the link for Google's Style Guide
  CONTRIBUTING.md
Labels: difficulty: easy, status: code review request, status: hacktoberfest approved

#610 chore: fix JDK Travis failures
  .travis.yml
Labels: status: code review request
