Repository sendgrid/sendgrid-java, pull requests merged in 2020-09, with the labels that each got.

#649 fix: update the eventwebhook sample data, example, tests, and byte handling
  examples/helpers/eventwebhook/Example.java
  src/main/java/com/sendgrid/helpers/eventwebhook/EventWebhook.java
  src/test/java/com/sendgrid/helpers/eventwebhook/EventWebhookTest.java
Labels: status: code review request

#504 docs: Update documentation for GET /templates
  USAGE.md
  examples/templates/templates.java
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved, type: docs update

#360 docs: reorganize examples
  examples/categories/README.md
  examples/categories/RetrieveAllCategories.java
  examples/categories/RetrieveStatisticsForCategories.java
  examples/categories/RetrieveSumsForCategories.java
  examples/categories/categories.java
Labels: difficulty: easy, status: code review request
